### ISSUE TITLE
Sessions don't save?

### ISSUE THREAD

**Issue by royjr** [eric-fraze/Alexa-PHP-Endpoint#2]
```
Alexa::remember('color', $color);
Alexa::recall('color');
```

Works fine, but once you stop talking to Alexa, and try to talk to it again, it doesnt remember.

What am I doing wrong?

**Comment by royjr** [comment]
Aha! So I see that userid tracking isn't built in to this.

**Comment by MayBeTall** [comment]
Yeah sessions only save for the one conversation with Alexa. Do you need
the userid tracking added in?

**Comment by royjr** [comment]
Thanks for the offer. I was able to get it working.. I've forked it. Let me know what you think. But yeah, I think it's should be in here.

**Comment by pattyland** [comment]
@royjr What about a pull request? ;)

**Comment by royjr** [comment]
https://github.com/MayBeTall/Alexa-PHP-Endpoint/pull/5

**Comment by royjr** [comment]
@pattyland any luck?

**Comment by pattyland** [comment]
I can't accept, this is not my project! 
I moved to another framework because I need cards and request verification (#4)
